FROM golang:1.16-alpine
EXPOSE 8080
WORKDIR /go/src/app
COPY ./material-applications/example-backend .
ENV REQUEST_ORIGIN=http://localhost:5000

RUN go build

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

CMD ["./server"]
