# newest node versions would not work
FROM node:16.20.0
EXPOSE 5000
WORKDIR /usr/src/app
COPY ./material-applications/example-frontend .

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt install -y nodejs
ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN node -v && npm -v
RUN npm install
RUN npm run build
RUN npm install -g serve

RUN useradd -m appuser
USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]
