# both example images were cloned (and built) again since something happened sionce the last time and they did not work
# also redis got its own volume and postgres options changed from defaults just for changes sake
version: "3.5"

services:
  frontend:
    build: ./frontend
    ports:
      - 5000:5000
    environment:
      - BACKEND_URL=http://localhost:80/

  backend:
    build: ./backend
    ports:
      - 8080:8080
      - 5432:5432
    environment:
      - FRONT_URL=http://localhost:80/
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=exampleUser
      - POSTGRES_PASSWORD=unsafeHere
      - POSTGRES_DATABASE=postgresDB
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    volumes:
      - ./redis_data:/data
    ports:
      - 6379:6379

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=unsafeHere
      - POSTGRES_USER=exampleUser
      - POSTGRES_DB=postgresDB
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  database:
  redis_data:
