version: "3.5"

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
    environment:
      - BACKEND_URL=http://localhost:8080

  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS_HOST=redis

  redis:
    image: "redis:alpine"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
