version: '3.5'

services: 
    frontend:
        image: frontend
        ports:
            - 5000:5000
        environment:
            - BACKEND_URL=http://localhost:8080
        
    backend:
        image: backend
        ports:
            - 8080:8080
        environment:
            - FRONT_URL=http://localhost:5000
