version: "3.5"

services:
  ml-kurkkumopo-frontend:
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000

  ml-kurkkumopo-backend:
    build: ./ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - training-model:/src/model
    restart: unless-stopped

  ml-kurkkumopo-training:
    build: ./ml-kurkkumopo-training
    volumes:
      - images:/src/imgs
      - training-model:/src/model

volumes:
  images:
  training-model:
