FROM alpine:latest
EXPOSE 8080
WORKDIR /go/src/app
COPY ./material-applications/example-backend .
ENV REQUEST_ORIGIN=http://localhost:5000

RUN apk add --no-cache go && \
    go build && \
    addgroup -S appgroup && \
    adduser -S appuser -G appgroup && \
    apk del go

USER appuser

CMD ["./server"]
